// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1Zh8S9o4v-6ONT67Yj2dQ2VuDI_kEghQ',
    appId: '1:960080112763:web:2f72db9e7173f9996d86de',
    messagingSenderId: '960080112763',
    projectId: 'amigo-eu-estou-aqui-4d4d0',
    authDomain: 'amigo-eu-estou-aqui-4d4d0.firebaseapp.com',
    storageBucket: 'amigo-eu-estou-aqui-4d4d0.firebasestorage.app',
    measurementId: 'G-KSNEGQ5LJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClvZxXIE9dUDZLOWS0qjj0Q0yK6KLat3Q',
    appId: '1:960080112763:android:21934c0cd14144df6d86de',
    messagingSenderId: '960080112763',
    projectId: 'amigo-eu-estou-aqui-4d4d0',
    storageBucket: 'amigo-eu-estou-aqui-4d4d0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqIYh4MFcWHrJYIjK90SrUKCygNdPKRrs',
    appId: '1:960080112763:ios:adf2d40f6a5738296d86de',
    messagingSenderId: '960080112763',
    projectId: 'amigo-eu-estou-aqui-4d4d0',
    storageBucket: 'amigo-eu-estou-aqui-4d4d0.firebasestorage.app',
    iosBundleId: 'com.example.companheiro',
  );
}
